<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>Hashx.Library.Tests</AssemblyName>
		<RootNamespace>Hashx.Library.Tests</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="xunit.v3" Version="4.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Library\Library.csproj" />
	</ItemGroup>

</Project>
