<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>Hashx.Application.Tests</AssemblyName>
		<RootNamespace>Hashx.Application.Tests</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="xunit.v3" Version="4.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Data\mock.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
