<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>hashx</AssemblyName>
		<RootNamespace>Hashx.Application</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<PropertyGroup>
		<PublishAot>true</PublishAot>
		<OptimizationPreference>speed</OptimizationPreference>
		<InvariantGlobalization>true</InvariantGlobalization>
		<StackTraceSupport>false</StackTraceSupport>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.CommandLine" Version="2.0.11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Library\Library.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Hashx.Application.Tests" />
	</ItemGroup>

</Project>
